service: aws-ruby-cron-with-dynamodb

frameworkVersion: '2'

provider:
  name: aws
  region: us-east-1
  runtime: ruby2.7
  memorySize: 256
  timeout: 10
  environment:
    SHARED_SECRET: shared_secret
    region: ${self:provider.region}
    service: ${self:service}
    tableName: ${self:custom.tableName}
  logRetentionInDays: 30
  tags:
    Application: ${self:service}
    Stage: ${sls:stage}
  lambdaHashingVersion: 20201221
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
          Resource:
            - 'arn:aws:dynamodb:::table/TABLE_NAME'

